//Product Action Types
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const DEFAULT_ORDER = "DEFAULT_ORDER";
export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT"
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ERROR = "ERROR";

//Category Action Types
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_SUB_CATEGORIES = "GET_SUB_CATEGORIES";
export const ERROR_CATEGORIES = "ERROR_CATEGORIES";
export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const EMPTY_CATEGORIES = "EMPTY_CATEGORIES";

//Company Info Action Types
export const GET_COMPANY_INFO = "GET_COMPANY_INFO";
export const SET_COMPANY_INFO = "SET_COMPANY_INFO";
export const LOADING_COMPANY_INFO = "LOADING_COMPANY_INFO";

//Complete Orders Action Types 
export const GET_COMPLETE_ORDERS = "GET_COMPLETE_ORDERS";
export const LOADING_COMPLETE_ORDERS = "LOADING_COMPLETE_ORDERS";
export const DELETE_COMPLETE_ORDER = "DELETE_COMPLETE_ORDER";
export const ERROR_COMPLETE_ORDERS = "ERROR_COMPLETE_ORDERS";
export const ADD_COMPLETE_ORDER = "ADD_COMPLETE_ORDER";
export const EDIT_COMPLETE_ORDER = "EDIT_COMPLETE_ORDER";

//Incomplete Order Action Types
export const GET_INCOMPLETE_ORDERS = "GET_INCOMPLETE_ORDERS";
export const LOADING_INCOMPLETE_ORDERS = "LOADING_INCOMPLETE_ORDERS";
export const DELETE_INCOMPLETE_ORDERS = "DELETE_INCOMPLETE_ORDERS";
export const ERROR_INCOMPLETE_ORDERS = "ERROR_INCOMPLETE_ORDERS";
export const EDIT_INCOMPLETE_ORDERS = "EDIT_INCOMPLETE_ORDERS";
export const ADD_TRACKING = "ADD_TRACKING";
export const ADD_INCOMPLETE_ORDER = "ADD_INCOMPLETE_ORDER";
export const EDIT_INCOMPLETE_ORDER = "EDIT_INCOMPLETE_ORDER";

